### ISSUE TITLE
Improve CLI error responses

### ISSUE THREAD

**Issue by ianfoster** [DLHub-Argonne/dlhub_cli#1]
The Globus CLI has the nice feature (IMHO) of providing usage information when commands are incomplete. Thus I can type:

    globus ls

and see usage:

    Usage: globus ls [OPTIONS] ENDPOINT_ID[:PATH]

**Comment by ryanchard** [comment]
Interestingly Stephen currently has a pull request out on Click to add this functionality to a command's definition: https://github.com/pallets/click/pull/1167

For now I'll just add it myself by checking if no arguments are set then later switch to Stephens solution once it is accepted.

**Comment by WardLT** [comment]
This was fixed in #7 as well.
