### ISSUE TITLE
Status for publish --repository

### ISSUE THREAD

**Issue by blaiszik** [DLHub-Argonne/dlhub_cli#3]
Checking status: `$dlhub status d4b11ebd-467b-4e93-9a2f-61a67d8da34c` shows `None` for servables published with --repository flag.

**Comment by ryanchard** [comment]
This should be fixed. The get_task_status function didn't seem to make it into the sdk's dlhubclient. That has now been added. Also, the command requires the task flag: dlhub status --task <task_id>.
